version: '3.8'
services:
  jekyll:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: jekyll
    volumes:
        - ./:/usr/blog
    command: sh -c 'bundle exec jekyll serve --host 0.0.0.0 --watch  --livereload'
    ports:
      - '4000:4000'
      - '35729:35729'